<?xml version="1.0" encoding="UTF-8" ?>
<!--DTD　内部声明-->
<!DOCTYPE scores[
        <!--元素：https://www.w3school.com.cn/dtd/dtd_elements.asp
        声明混合型的内容：
        <!ELEMENT student (#PCDATA|to|from|header|message)*>
        其声明了："student" 元素可包含出现零次或多次的 PCDATA、"to"、"from"、"header" 或者 "message"。
        -->
        <!--student+ 表示至少有一个student元素-->
        <!--student* 表示至少有零个student元素-->
        <!--student? 表示至多一个student元素-->
        <!ELEMENT scores (student)+ >
        <!ELEMENT student (name,age,remark) >
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT remark (#PCDATA)>
        <!--属性: https://www.w3school.com.cn/dtd/dtd_attributes.asp
        属性值 选择
        值	            属性的默认值
        #REQUIRED	    属性值是必需的
        #IMPLIED	    属性不是必需的
        #FIXED value	属性值是固定的
        -->
        <!ATTLIST student id ID #IMPLIED>
        ]>
<scores>
    <student id="s1">
        <name>eric</name>
        <age>23</age>
        <!-- <![CDATA[震惊部UC]]> 内容 “震惊部UC”不会被解析替换，保持原始内容 -->
        <remark><![CDATA[震惊部UC]]></remark>
    </student>
    <student id="s2">
        <name>bob</name>
        <age>25</age>
        <!-- <![CDATA[震惊部UC]]> 内容 “震惊部UC”不会被解析替换，保持原始内容 -->
        <remark><![CDATA[震惊部UC]]></remark>
    </student>
    <student id="s3">
        <name>danny</name>
        <age>23</age>
        <!-- <![CDATA[震惊部UC]]> 内容 “震惊部UC”不会被解析替换，保持原始内容 -->
        <remark><![CDATA[震惊部UC]]></remark>
    </student>
    <student id="s4">
        <name>Jane</name>
        <age>36</age>
        <!-- <![CDATA[震惊部UC]]> 内容 “震惊部UC”不会被解析替换，保持原始内容 -->
        <remark><![CDATA[震惊部UC]]></remark>
    </student>
</scores>